# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

# =============================================================================
# NetApp DR Starter Kit - Infrastructure Targets
# =============================================================================
#
# These targets manage the DR infrastructure via Crossplane (GitOps):
#   - Cluster discovery (auto-detect VPC, CIDR, region from kubeconfigs)
#   - Crossplane values written to Helm values files
#   - ArgoCD syncs Crossplane managed resources (FSx, S3, VPC Peering, Route53)
#
# Required:
#   PROD_KUBECONFIG - path to production cluster kubeconfig
#   DR_KUBECONFIG   - path to DR cluster kubeconfig
# =============================================================================

# Expand ~ in kubeconfig paths
PROD_KUBECONFIG ?=
DR_KUBECONFIG ?=
_PROD_KUBECONFIG := $(if $(PROD_KUBECONFIG),$(shell echo $(PROD_KUBECONFIG)),)
_DR_KUBECONFIG := $(if $(DR_KUBECONFIG),$(shell echo $(DR_KUBECONFIG)),)
EXTRA_PLAYBOOK_OPTS ?=

# Optional overrides (empty = auto-detect from cluster)
PROD_CLUSTER ?=
DR_CLUSTER ?=
PROD_REGION ?=
DR_REGION ?=
PROD_VPC_CIDR ?=
DR_VPC_CIDR ?=

# Build the -e extra-vars string from overrides
_DR_EXTRA_VARS := -e prod_kubeconfig=$(_PROD_KUBECONFIG) -e dr_kubeconfig=$(_DR_KUBECONFIG)
ifneq ($(PROD_CLUSTER),)
  _DR_EXTRA_VARS += -e prod_cluster_name_override=$(PROD_CLUSTER)
endif
ifneq ($(DR_CLUSTER),)
  _DR_EXTRA_VARS += -e dr_cluster_name_override=$(DR_CLUSTER)
endif
ifneq ($(PROD_REGION),)
  _DR_EXTRA_VARS += -e prod_region_override=$(PROD_REGION)
endif
ifneq ($(DR_REGION),)
  _DR_EXTRA_VARS += -e dr_region_override=$(DR_REGION)
endif
ifneq ($(PROD_VPC_CIDR),)
  _DR_EXTRA_VARS += -e prod_vpc_cidr_override=$(PROD_VPC_CIDR)
endif
ifneq ($(DR_VPC_CIDR),)
  _DR_EXTRA_VARS += -e dr_vpc_cidr_override=$(DR_VPC_CIDR)
endif

# Validation
define _validate_kubeconfigs
	@if [ -z "$(_PROD_KUBECONFIG)" ]; then \
		echo "Error: PROD_KUBECONFIG is required."; \
		echo "Usage: make $(1) PROD_KUBECONFIG=/path/to/prod DR_KUBECONFIG=/path/to/dr"; \
		exit 1; \
	fi
	@if [ -z "$(_DR_KUBECONFIG)" ]; then \
		echo "Error: DR_KUBECONFIG is required."; \
		echo "Usage: make $(1) PROD_KUBECONFIG=/path/to/prod DR_KUBECONFIG=/path/to/dr"; \
		exit 1; \
	fi
	@if [ ! -f "$(_PROD_KUBECONFIG)" ]; then \
		echo "Error: PROD_KUBECONFIG file not found: $(_PROD_KUBECONFIG)"; \
		exit 1; \
	fi
	@if [ ! -f "$(_DR_KUBECONFIG)" ]; then \
		echo "Error: DR_KUBECONFIG file not found: $(_DR_KUBECONFIG)"; \
		exit 1; \
	fi
endef

##@ NetApp DR Infrastructure

##@ Crossplane Infrastructure

.PHONY: crossplane-setup
crossplane-setup: ## Discover clusters and write Crossplane values (then commit+push for ArgoCD)
	$(call _validate_kubeconfigs,crossplane-setup)
	@echo "=========================================="
	@echo "Crossplane Infrastructure Setup"
	@echo "  Prod kubeconfig: $(_PROD_KUBECONFIG)"
	@echo "  DR kubeconfig:   $(_DR_KUBECONFIG)"
	@echo "  (Route53: configure AWS credentials for hosted-zone discovery — no zone ID in Git)"
	@echo "=========================================="
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/crossplane-setup.yaml \
		-e @ansible/crossplane-vars.yml \
		$(_DR_EXTRA_VARS)
	@echo ""
	@echo "=========================================="
	@echo "  Values files updated. Next steps:"
	@echo "    1. git diff  (review changes)"
	@echo "    2. git add -A && git commit"
	@echo "    3. git push  (triggers ArgoCD sync)"
	@echo "    4. kubectl get managed  (monitor)"
	@echo "=========================================="

##@ Crossplane DR Teardown

.PHONY: destroy-dr dr-destroy
# dr-destroy is an alias (same recipe as destroy-dr)
destroy-dr dr-destroy: ## Destroy DR infrastructure (pauses ArgoCD, cleans ONTAP, deletes Crossplane resources)
	$(call _validate_kubeconfigs,destroy-dr)
	@echo "=========================================="
	@echo "WARNING: Destroying DR Infrastructure"
	@echo "=========================================="
	@echo "  Prod kubeconfig: $(_PROD_KUBECONFIG)"
	@echo "  DR kubeconfig:   $(_DR_KUBECONFIG)"
	@echo ""
	@echo "  This will:"
	@echo "    1. Pause ArgoCD auto-sync on both clusters"
	@echo "    2. Clean up ONTAP (SnapMirror, volumes, peers)"
	@echo "    3. Scrub AppVault S3 bucket"
	@echo "    4. Delete Crossplane-managed AWS resources (hub oc delete)"
	@echo "    5. AWS CLI fallback: remove any remaining FSx + VPC peering by tag/VPC pair"
	@echo "       (playbook fails if they still exist — needs aws configure / env creds)"
	@echo "=========================================="
	@echo ""
	@read -p "Type 'yes' to confirm: " confirm && [ "$$confirm" = "yes" ] || (echo "Aborted."; exit 1)
	ansible-playbook $(EXTRA_PLAYBOOK_OPTS) ansible/crossplane-destroy.yaml \
		-e @ansible/crossplane-vars.yml \
		$(_DR_EXTRA_VARS)

##@ Code quality (Biome — JSON formatter parity with GitHub super-linter v8)

.PHONY: deps-js lint-biome format-biome

deps-js: ## Install Node devDependencies (Biome); uses package-lock.json
	npm ci

lint-biome: deps-js ## Run Biome check (format + lint) on the repo
	npm run lint:biome

format-biome: deps-js ## Write Biome formatting (e.g. Grafana dashboard JSON)
	npm run format:biome
