apiVersion: v2
name: crossplane
description: Crossplane deployment for validated patterns framework (OpenShift)
type: application
version: 0.1.0
appVersion: "2.2.0"

dependencies:
  - name: crossplane
    version: 2.2.*
    repository: https://charts.crossplane.io/stable
