{{- range .Values.tridentProtect.backups }}
---
apiVersion: protect.trident.netapp.io/v1
kind: Backup
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default .applicationRef }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  applicationRef: {{ .applicationRef }}
  appVaultRef: {{ .appVaultRef }}
  {{- if .dataMover }}
  dataMover: {{ .dataMover }}
  {{- end }}
  {{- if .reclaimPolicy }}
  reclaimPolicy: {{ .reclaimPolicy }}
  {{- end }}
  {{- if .snapshotRef }}
  snapshotRef: {{ .snapshotRef }}
  {{- end }}
{{- end }}
