{{- range .Values.tridentProtect.schedules }}
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default .applicationRef }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  applicationRef: {{ .applicationRef }}
  appVaultRef: {{ .appVaultRef }}
  granularity: {{ .granularity | default "Hourly" }}
  {{- if .minute }}
  minute: {{ .minute | quote }}
  {{- end }}
  {{- if .hour }}
  hour: {{ .hour | quote }}
  {{- end }}
  {{- if .dayOfWeek }}
  dayOfWeek: {{ .dayOfWeek | quote }}
  {{- end }}
  {{- if .dayOfMonth }}
  dayOfMonth: {{ .dayOfMonth | quote }}
  {{- end }}
  snapshotRetention: {{ .snapshotRetention | default "24" | quote }}
  backupRetention: {{ .backupRetention | default "7" | quote }}
  {{- if .dataMover }}
  dataMover: {{ .dataMover }}
  {{- end }}
  {{- if hasKey . "enabled" }}
  enabled: {{ .enabled }}
  {{- end }}
{{- end }}
