{{- range .Values.tridentProtect.snapshots }}
---
apiVersion: protect.trident.netapp.io/v1
kind: Snapshot
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default .applicationRef }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  applicationRef: {{ .applicationRef }}
  appVaultRef: {{ .appVaultRef }}
  {{- if .reclaimPolicy }}
  reclaimPolicy: {{ .reclaimPolicy }}
  {{- end }}
{{- end }}
