{{- if .Values.drDnsReconciler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-dns-reconciler
  namespace: {{ .Values.drDnsReconciler.namespace }}
  labels:
    {{- include "dr-dns-reconciler.labels" . | nindent 4 }}
{{- end }}
