{{- range .Values.crossplane.providers.packages }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: "{{ .package }}:{{ $.Values.crossplane.providers.version }}"
  runtimeConfigRef:
    name: aws-runtime-config
{{- end }}
