{{- if .Values.fsxOntap.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fsx-credentials
  namespace: {{ .Values.fsxOntap.passwordSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.fsxOntap.passwordSecret.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{ .Values.fsxOntap.passwordSecret.fsxAdminKey }}: "{{`{{ .password | trim }}`}}"
        {{ .Values.fsxOntap.passwordSecret.svmAdminKey }}: "{{`{{ .password | trim }}`}}"
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/global/fsx-admin
        property: content
{{- end }}
