# ExternalSecret Configuration
secretStoreRef:
  name: vault-backend
  kind: ClusterSecretStore

wordpressSecret:
  name: wordpress-password
  vaultKey: secret/data/global/wordpress
  property: password

mariadbSecret:
  name: wordpress-mariadb
  vaultKey: secret/data/global/wordpress
  rootProperty: rootPassword
  property: mariadbPassword

wordpress:
  wordpressUsername: admin
  wordpressBlogName: "Best Blog Ever"

  existingSecret: wordpress-password

  updateStrategy:
    type: Recreate

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 768Mi

  global:
    storageClass: storage-class-nfs
    security:
      allowInsecureImages: true

  image:
    registry: quay.io
    repository: validatedpatterns/wordpress
    tag: 6.9.1
    debug: true

  mariadb:
    auth:
      existingSecret: wordpress-mariadb
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 768Mi
    image:
      registry: quay.io
      repository: validatedpatterns/mariadb
      tag: 12.2.2

  ingress:
    enabled: false

